In [ ]:
# create an array of 3 rows and 3 coloumns

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy

In [5]:

numbers=[[1,2,3],[4,5,6],[7,8,9]]

array=numpy.array(numbers)

print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(array[1,2])
print(array[-1])
print(array[:,-1]) # when you dont want to give value for row 
print(array[1,:])

6
[7 8 9]
[3 6 9]
[4 5 6]


slicing 
========

In [11]:
print(array[0:2])
print(array[:,1::])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


select last two rows

In [12]:
print(array[1::])

[[4 5 6]
 [7 8 9]]


select first two coloumns

In [13]:
print(array[:,0:2])

[[1 2]
 [4 5]
 [7 8]]


create a 4 by 4 array

In [14]:
numbers=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

array_numbers=numpy.array(numbers)

print(array_numbers)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
print(array_numbers[0:2,2::])

[[3 4]
 [7 8]]


In [16]:
print(array_numbers[0:3,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [18]:
print(array_numbers[2::,1::])

[[10 11 12]
 [14 15 16]]


In [19]:
array_numbers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Functions
=========

In [ ]:
# array_numbers.mean()
# array_numbers.min()
# array_numbers.max()
# array_numbers.dtype
# array_numbers.shape
# array_numbers.ndim   shows the dimension of the array

2

create a 4 by 4 matrix

In [31]:
numbers=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

matrix=numpy.array(numbers)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


print first row

In [29]:
print(matrix[1])

[5 6 7 8]


print last coloumn

In [30]:
print(matrix[:,-1])

[ 4  8 12 16]


print first two rows and first three coloumns using slicing

In [32]:
print(matrix[0:2,0:3])

[[1 2 3]
 [5 6 7]]


sum of all elements

In [33]:
print(matrix.sum())

136


min and max of array

In [34]:
print(matrix.min())
print(matrix.max())

1
16


average of all elements

In [35]:
print(matrix.mean())

8.5


sum of first row

In [38]:
s=matrix[0]
print(s.sum())


10


sum of last coloumn

In [39]:
s=matrix[:,-1]

print(s.sum())

40


sum of last two rows

In [40]:
s=matrix[2::]
print(s.sum())

100


create a new array with each element multiplied by two

In [41]:
s=matrix*2
print(s)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
