create a 4 by 4 matrix

display the last coloumn
display the first 2 rows
sum of first two rows
avg of last two coloumns
max and min of third column

In [2]:
import numpy

In [ ]:
# create a 4 by 4 matrix

numbers=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

array_numbers=numpy.array(numbers)
print(array_numbers)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#display the last coloumn

print(array_numbers[:,-1])

[ 4  8 12 16]


In [ ]:
#display the first 2 rows

print(array_numbers[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# sum of first two rows

s=array_numbers[0:2]
print(s.sum())

36


In [ ]:
# avg of last two coloumns

s=array_numbers[:,2::]

print(s.mean())

9.5


In [ ]:
# max and min of third column

s=array_numbers[:,2]
print(s.min())
print(s.max())

3
15


Given a list of numbers , to create a new list that contains only even numbers from yhe original list , but if an even number is greater than 10 , it should be replaced with a string 'BIG'

numbers=[1,4,12,8,15,20,3]

In [9]:
numbers=[1,4,12,8,15,20,3]
even=[]

for i in numbers:

    if i%2==0:

        if i>10:

            even.append("BIG")
        else:
            even.append(i)

print(even)



[4, 'BIG', 8, 'BIG']


In [10]:
print(array_numbers)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
# filter the numbers which are greater than 10 

array_numbers[array_numbers>10]

array([11, 12, 13, 14, 15, 16])

In [ ]:
# odd numbers in the first row

array_numbers[0][array_numbers[0] % 2 != 0]

array([1, 3])

In [13]:
# sum of odd numbers in the first row

array_numbers[0][array_numbers[0] % 2 != 0].sum()

np.int64(4)

create 3 by 4 matrix

In [ ]:
# random is a module in numpy
# random module contains randint used to pick random numbers between low and high
# here 1 is low , 50 is high and size is 3 by 4 , 3 rows and 4 coloumns

n=numpy.random.randint(1,50,size=(3,4))  

print(n)

[[24 33 46  9]
 [ 5 36  6  2]
 [11  3  5 28]]


In [4]:
print(numpy.arange(1,11)) #used to generate squence of numbers from start to stop

[ 1  2  3  4  5  6  7  8  9 10]


Types of Matrices
==================


Zero matrix
One matrix
Identity matrix

In [7]:
n=numpy.zeros((3,4),dtype=int)  # x=3 and y=4 contaons all elements as zero
print(n)

a=numpy.ones((5,4),dtype=int)   # x=5 and y=4 contains all elements as one
print(a)

b=numpy.identity(4)  # identity matrix is possible only for square matrix.It takes only one argument
print(b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# create a 4 by 3 matrix

n=numpy.random.randint(1,20,size=(4,3))
print(n)

[[12 13  8]
 [ 6  7  7]
 [18  7  7]
 [10  9 18]]


In [13]:
# Change 13 to 16

n[0,1]=16
n
n[1]=16
n

array([[12, 16,  8],
       [16, 16, 16],
       [18,  7,  7],
       [10,  9, 18]], dtype=int32)

In [19]:
a=numpy.sum(n,axis=0)  # axis = 0 for coloumn wise
b=numpy.sum(n,axis=1)  # axis = 1 for row wise
print(a)
print(b)

[56 48 49]
[36 48 32 37]


In [20]:
n=numpy.random.randint(1,50,size=(4,3))
m=numpy.random.randint(1,50,size=(4,3))
print(n)
print(m)

[[ 5 31 18]
 [27 19 42]
 [ 9 42  5]
 [20 47 42]]
[[41 10 31]
 [22 22 13]
 [42 49 10]
 [21 19 38]]


In [ ]:
# Add arrays n and m

print(numpy.add(n,m))  # To add two arrays the two arrays should have the same shape 

# add 10 to all the values in array m
s=m+10
print(s)

[[46 41 49]
 [49 41 55]
 [51 91 15]
 [41 66 80]]
[[51 20 41]
 [32 32 23]
 [52 59 20]
 [31 29 48]]


In [24]:
print(n)

[[ 5 31 18]
 [27 19 42]
 [ 9 42  5]
 [20 47 42]]


In [26]:
print(numpy.sqrt(n)) # To get the squareroot of each value in the array n 

[[2.23606798 5.56776436 4.24264069]
 [5.19615242 4.35889894 6.4807407 ]
 [3.         6.4807407  2.23606798]
 [4.47213595 6.8556546  6.4807407 ]]


In [ ]:
print(numpy.mean(n))  # mean is the average. Here it calculates the average value from the array n

25.583333333333332


In [28]:
print(numpy.std(n)) # std is standard deviation

14.585714091382552


In [30]:
# Find the squareroot of the elements in the first row

first_row=n[0]
print(first_row)
print(numpy.sqrt(first_row))

[ 5 31 18]
[2.23606798 5.56776436 4.24264069]


In [31]:
# Find the mean of elements in the first two rows

numpy.mean(n[0:2])

np.float64(23.666666666666668)

In [32]:
n

array([[ 5, 31, 18],
       [27, 19, 42],
       [ 9, 42,  5],
       [20, 47, 42]], dtype=int32)

In [ ]:
# numbers greater than 20 and are even numbers

print(n[(n%2==0) & (n>20)])   

# numbers greater than 20 or are even numbers

print(n[(n%2==0) | (n>20)])

[42 42 42]
[31 18 27 42 42 20 47 42]


create a array of 4 by 4 of values from 10 to 25

display the array
find the row sum and coloumn sum
display the elements greater than 18 and less than 23
replace all elements greater than 20 with 0
find all elements that are odd or divisble by 5
calculate the sum of last two rows
extract 2nd and 3rd coloumn
add all the elements in array with mean of the array

In [35]:
n=numpy.random.randint(10,25,size=(4,4))
print(n)

[[23 19 23 13]
 [10 13 10 12]
 [17 11 18 13]
 [23 20 16 17]]


In [37]:
print(numpy.sum(n,axis=0))
print(numpy.sum(n,axis=1))

[73 63 67 55]
[78 45 59 76]


In [38]:
print(n[(n>18) & (n<23)])

[19 20]


In [40]:
n[n>20]=0
print(n)

[[ 0 19  0 13]
 [10 13 10 12]
 [17 11 18 13]
 [ 0 20 16 17]]


In [41]:
print(n[(n%2 !=0) | (n%5 == 0)])

[ 0 19  0 13 10 13 10 17 11 13  0 20 17]


In [42]:
print(numpy.sum(n[2::]))

112


In [43]:
print(n[:,1:3])

[[19  0]
 [13 10]
 [11 18]
 [20 16]]


In [ ]:
n + numpy.mean(n)

array([[11.8125, 30.8125, 11.8125, 24.8125],
       [21.8125, 24.8125, 21.8125, 23.8125],
       [28.8125, 22.8125, 29.8125, 24.8125],
       [11.8125, 31.8125, 27.8125, 28.8125]])