In [1]:
print("hello world")

hello world


what is numpy

use of numerical values in data science

difference between array and list

ipynb advantages


create an array of numbers from 1 to 10

In [1]:
import numpy

numbers=list(range(1,11))
array_numbers=numpy.array(numbers)

print(array_numbers)

[ 1  2  3  4  5  6  7  8  9 10]


create an array of odd numbers from 1 to n. n should be entered by user

In [6]:
n=int(input("Enter the limit : "))

odd_numbers=[i for i in range(1,n+1) if i%2!=0]

odd_array=numpy.array(odd_numbers)

print(odd_array)

[ 1  3  5  7  9 11 13 15 17 19]


Types of arrays
===============

one dimensional array  >> [1,2,3,4,5,6,7,8,9]

two dimensional array  >> [[1,2,3,4],[3,4,5,6]]

three dimensional array >> [[[1,2,3,4],[3,4,5,6],[1,2,3,4],[3,4,5,6]]]

In [8]:
numbers= [[1,2,3,4],[3,4,5,6]]

result=numpy.array(numbers)

print(result)

print(result.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


create a 2d array of 4 rows and 3 coloumns

In [9]:
numbers=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

result=numpy.array(numbers)

print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
